easy_admin:
  site_name: '<a href="/">Niners Brutal Admin</a>'
  user:
    display_name: true
    display_avatar: true
    avatar_property_path: 'getAvatar'
  entities:
      - App\Entity\User
      - App\Entity\Team
