vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: /imagesRepository
            upload_destination: '%kernel.project_dir%/public/imagesRepository'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
